// Generated by scripts/build-ax.mjs from data/catalog.json.
(function () {
  "use strict";
  var products = {
  "FG-011": {
    "ref": "FG-011",
    "slug": "vipera-emerald-ring",
    "name": "Vipera Ring",
    "category": "Rings",
    "price": "AED 12,500",
    "priceValue": 12500,
    "currency": "AED",
    "sub": "Step-cut emerald, diamond halo",
    "sizes": true,
    "img": "assets/img/vipera.jpg",
    "imgW": 1200,
    "imgH": 1600,
    "imgAlt": "The Vipera Ring, a step-cut emerald in a diamond halo, photographed on white seamless",
    "desc": "A single step-cut emerald held in a halo of brilliants, cut to the original 2026 drawing. The band is round in section, heavier than it looks, quieter than it sounds. Plate FG-011 in the maison ledger.",
    "materials": [
      "Muzo-origin emerald, 1.2 ct, step cut",
      "Halo of recycled brilliants, 0.4 ct total",
      "Recycled platinum 950, round-section band"
    ],
    "plate": "vipera",
    "plateBox": "0 0 240 240",
    "related": [
      "FG-014",
      "FG-021",
      "FG-033"
    ]
  },
  "FG-014": {
    "ref": "FG-014",
    "slug": "meridian-diamond-band",
    "name": "Meridian Band",
    "category": "Rings",
    "price": "AED 6,800",
    "priceValue": 6800,
    "currency": "AED",
    "sub": "Pave-set band, satin platinum",
    "sizes": true,
    "img": "assets/img/meridian.jpg",
    "imgW": 1200,
    "imgH": 800,
    "imgAlt": "The Meridian Band, a wide pave-set band photographed on black",
    "desc": "A full turn of pave, set flush so the band reads as one unbroken surface of light. A single hairline groove, the meridian, runs the circumference. Plate FG-014 in the maison ledger.",
    "materials": [
      "Recycled brilliants, 1.1 ct total, flush pave",
      "Recycled platinum 950, satin interior",
      "Engraved meridian groove, hand-cut"
    ],
    "plate": "meridian",
    "plateBox": "0 0 200 200",
    "related": [
      "FG-011",
      "FG-041",
      "FG-031"
    ]
  },
  "FG-021": {
    "ref": "FG-021",
    "slug": "lumen-emerald-pendant",
    "name": "Lumen Pendant",
    "category": "Necklaces",
    "price": "AED 10,650",
    "priceValue": 10650,
    "currency": "AED",
    "sub": "Emerald drop, hand-drawn chain",
    "sizes": false,
    "img": "assets/img/lumen.jpg",
    "imgW": 1200,
    "imgH": 1200,
    "imgAlt": "The Lumen Pendant, an emerald drop on a fine chain, resting on deep green cloth",
    "desc": "A step-cut emerald hung from a trace chain fine enough to disappear, so the stone appears to rest on the collarbone by agreement rather than engineering. Adjustable 42-45 cm. Plate FG-021 in the maison ledger.",
    "materials": [
      "Muzo-origin emerald, 0.9 ct, step cut",
      "Recycled platinum trace chain, 42-45 cm",
      "Clasp engraved with the plate number"
    ],
    "plate": "lumen",
    "plateBox": "0 0 220 280",
    "related": [
      "FG-024",
      "FG-011",
      "FG-043"
    ]
  },
  "FG-024": {
    "ref": "FG-024",
    "slug": "voss-emerald-collier",
    "name": "Voss Collier",
    "category": "Necklaces",
    "price": "AED 33,800",
    "priceValue": 33800,
    "currency": "AED",
    "sub": "Diamond fringe, emerald drops",
    "sizes": false,
    "img": "assets/img/voss.jpg",
    "imgW": 1200,
    "imgH": 800,
    "imgAlt": "The Voss Collier, a diamond fringe necklace with emerald drops",
    "desc": "The largest piece in the ledger: a fringe of baguettes that moves like water, carrying three graduated emerald drops. Made for occasions that do not repeat. Plate FG-024 in the maison ledger.",
    "materials": [
      "Three graduated Muzo emeralds, 3.1 ct total",
      "Baguette fringe, recycled stones throughout",
      "Recycled platinum 950, articulated links"
    ],
    "plate": "voss",
    "plateBox": "0 0 220 170",
    "related": [
      "FG-021",
      "FG-033",
      "FG-041"
    ]
  },
  "FG-031": {
    "ref": "FG-031",
    "slug": "eos-diamond-earrings",
    "name": "Eos Earrings",
    "category": "Earrings",
    "price": "AED 4,250",
    "priceValue": 4250,
    "currency": "AED",
    "sub": "Chevron pave, recycled platinum",
    "sizes": false,
    "img": "assets/img/eos.jpg",
    "imgW": 1200,
    "imgH": 800,
    "imgAlt": "The Eos Earrings, pave chevron drops photographed on black",
    "desc": "Disc drops set with chevron rows of pave, angled so they catch light on the turn of the head rather than head-on. Worn daily by everyone who has ever tried them. Plate FG-031 in the maison ledger.",
    "materials": [
      "Recycled brilliants in chevron pave",
      "Recycled platinum 950 discs and posts",
      "Butterfly backs, engraved"
    ],
    "plate": "eos",
    "plateBox": "0 0 200 200",
    "related": [
      "FG-033",
      "FG-021",
      "FG-014"
    ]
  },
  "FG-033": {
    "ref": "FG-033",
    "slug": "thalis-emerald-drop-earrings",
    "name": "Thalis Drops",
    "category": "Earrings",
    "price": "AED 6,050",
    "priceValue": 6050,
    "currency": "AED",
    "sub": "Pear-cut emeralds, articulated",
    "sizes": false,
    "img": "assets/img/thalis.jpg",
    "imgW": 1200,
    "imgH": 1200,
    "imgAlt": "The Thalis Drops, green teardrop earrings in ornate settings",
    "desc": "Pear-cut emeralds in openwork settings, articulated at the shoulder so the drops swing a half-beat behind the wearer. The drawing took eleven attempts; the movement was the hard part. Plate FG-033 in the maison ledger.",
    "materials": [
      "Pear-cut emeralds, 2.4 ct total",
      "Openwork recycled platinum settings",
      "Articulated at post and shoulder"
    ],
    "plate": "thalis",
    "plateBox": "0 0 200 220",
    "related": [
      "FG-031",
      "FG-024",
      "FG-011"
    ]
  },
  "FG-041": {
    "ref": "FG-041",
    "slug": "sable-blackened-platinum-cuff",
    "name": "Sable Cuff",
    "category": "Bracelets",
    "price": "AED 7,900",
    "priceValue": 7900,
    "currency": "AED",
    "sub": "Pave open cuff, blackened platinum",
    "sizes": false,
    "img": "assets/img/sable.jpg",
    "imgW": 1200,
    "imgH": 800,
    "imgAlt": "The Sable Cuff, an open pave cuff on a black reflective surface",
    "desc": "An open cuff in blackened platinum with a single spine of pave. The blackening wears at the high points over years, and the piece records its owner. Plate FG-041 in the maison ledger.",
    "materials": [
      "Recycled platinum 950, blackened finish",
      "Pave spine of recycled brilliants",
      "Sprung opening, sized to the wrist at fitting"
    ],
    "plate": "sable",
    "plateBox": "0 0 200 200",
    "related": [
      "FG-043",
      "FG-014",
      "FG-031"
    ]
  },
  "FG-043": {
    "ref": "FG-043",
    "slug": "rill-diamond-line-bracelet",
    "name": "Rill Chain",
    "category": "Bracelets",
    "price": "AED 6,950",
    "priceValue": 6950,
    "currency": "AED",
    "sub": "Diamond line bracelet, five stations",
    "sizes": false,
    "img": "assets/img/rill.jpg",
    "imgW": 1200,
    "imgH": 675,
    "imgAlt": "The Rill Chain, a fine diamond line bracelet on black",
    "desc": "A line bracelet fine as running water, interrupted five times by set stones, the stations. Fastens with a hidden box clasp that closes with a watchmaker's click. Plate FG-043 in the maison ledger.",
    "materials": [
      "Five station-set recycled brilliants",
      "Recycled platinum 950 line links",
      "Hidden box clasp, engraved"
    ],
    "plate": "rill",
    "plateBox": "0 0 220 130",
    "related": [
      "FG-041",
      "FG-021",
      "FG-031"
    ]
  }
};
  var root = document.documentElement.getAttribute("data-site-root") || "";
  Object.keys(products).forEach(function (ref) {
    products[ref].img = root + products[ref].img;
    products[ref].href = root + "pieces/" + products[ref].slug + "/";
  });
  window.FROZI_CATALOG = { products: products };
})();
